#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Sat Aug 24 13:39:09 2019
#

import wx
from wx.lib.pubsub import pub
import os

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import mapPanel
# end wxGlade

import rotorCom

rotor = 0

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CLIP_CHILDREN | wx.FRAME_TOOL_WINDOW | wx.RESIZE_BORDER | wx.NO_BORDER
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 479))
        self.lblNewSetPoint = wx.StaticText(self, wx.ID_ANY, u"New set point: 145\u00b0")
        self.btnSetUpper = wx.Button(self, wx.ID_ANY, "Set upper rotor")
        self.btnSetLower = wx.Button(self, wx.ID_ANY, "Set lower rotor")
        self.btnCancel = wx.Button(self, wx.ID_ANY, "Cancel")
        self.map = mapPanel.MapPanel(self, wx.ID_ANY)
        self.btnSetLocation = wx.Button(self, wx.ID_ANY, "Location: JO63PA")
        self.lblUpSetPoint = wx.StaticText(self, wx.ID_ANY, u"Set Point: 276.5\u00b0")
        self.lblUpPosition = wx.StaticText(self, wx.ID_ANY, u"Position: 234.4\u00b0")
        self.lblUpCurrent = wx.StaticText(self, wx.ID_ANY, "Current: 123 mA")
        self.btnUpperRef = wx.Button(self, wx.ID_ANY, "Ref", style=wx.BU_EXACTFIT)
        self.btnUpperStop = wx.Button(self, wx.ID_ANY, "Stop", style=wx.BU_EXACTFIT)
        self.lblDownSetPoint = wx.StaticText(self, wx.ID_ANY, u"Set Point: 276.5\u00b0")
        self.lblDownPosition = wx.StaticText(self, wx.ID_ANY, u"Position: 234.4\u00b0")
        self.lblDownCurrent = wx.StaticText(self, wx.ID_ANY, "Current: 123 mA")
        self.btnLowerRef = wx.Button(self, wx.ID_ANY, "Ref", style=wx.BU_EXACTFIT)
        self.btnLowerStop = wx.Button(self, wx.ID_ANY, "Stop", style=wx.BU_EXACTFIT)
        self.btnExit = wx.Button(self, wx.ID_ANY, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_set_upper, self.btnSetUpper)
        self.Bind(wx.EVT_BUTTON, self.on_set_lower, self.btnSetLower)
        self.Bind(wx.EVT_BUTTON, self.on_cancel, self.btnCancel)
        self.Bind(wx.EVT_BUTTON, self.on_set_location, self.btnSetLocation)
        self.Bind(wx.EVT_BUTTON, self.on_upper_ref, self.btnUpperRef)
        self.Bind(wx.EVT_BUTTON, self.on_upper_stop, self.btnUpperStop)
        self.Bind(wx.EVT_BUTTON, self.on_lower_ref, self.btnLowerRef)
        self.Bind(wx.EVT_BUTTON, self.on_lower_stop, self.btnLowerStop)
        self.Bind(wx.EVT_BUTTON, self.on_exit, self.btnExit)
        # end wxGlade

        # create a pubsub receiver
        pub.subscribe(self.updateDisplay, "update")

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Antenna Controller")
        self.btnUpperStop.SetBackgroundColour(wx.Colour(255, 142, 127))
        self.btnLowerStop.SetBackgroundColour(wx.Colour(255, 142, 127))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Lower Rotor"), wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Upper Rotor"), wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Control"), wx.VERTICAL)
        sizer_10.Add(self.lblNewSetPoint, 0, wx.LEFT | wx.RIGHT | wx.TOP, 5)
        sizer_10.Add(self.btnSetUpper, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)
        sizer_10.Add(self.btnSetLower, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)
        sizer_10.Add(self.btnCancel, 0, wx.ALL | wx.EXPAND, 5)
        sizer_8.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_8.Add(self.map, 1, wx.ALL | wx.EXPAND, 5)
        sizer_9.Add(self.btnSetLocation, 0, wx.EXPAND, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, "")
        label_1.SetBackgroundColour(wx.Colour(70, 180, 70))
        sizer_11.Add(label_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_11.Add(self.lblUpSetPoint, 0, wx.ALL, 5)
        sizer_11.Add(self.lblUpPosition, 0, wx.ALL, 5)
        sizer_11.Add(self.lblUpCurrent, 0, wx.ALL, 5)
        sizer_15.Add(self.btnUpperRef, 0, wx.ALL, 5)
        sizer_15.Add(self.btnUpperStop, 0, wx.ALL, 5)
        sizer_11.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_11, 0, wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "")
        label_2.SetBackgroundColour(wx.Colour(0, 0, 255))
        sizer_13.Add(label_2, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)
        sizer_13.Add(self.lblDownSetPoint, 0, wx.ALL, 5)
        sizer_13.Add(self.lblDownPosition, 0, wx.ALL, 5)
        sizer_13.Add(self.lblDownCurrent, 0, wx.ALL, 5)
        sizer_16.Add(self.btnLowerRef, 0, wx.ALL, 5)
        sizer_16.Add(self.btnLowerStop, 0, wx.ALL, 5)
        sizer_13.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_9.Add((20, 20), 1, 0, 0)
        sizer_14.Add((20, 20), 1, 0, 0)
        sizer_14.Add(self.btnExit, 0, wx.ALL, 5)
        sizer_9.Add(sizer_14, 0, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 0, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7)
        self.Layout()
        # end wxGlade
        self.map.SetpointCallback(self.OnNewSetpoint)
        self.UpdateSetpoint()

    def on_cancel(self, event):  # wxGlade: MainFrame.<event_handler>
        self.map.newSetpoint = -1
        self.UpdateSetpoint()
        event.Skip()

    def on_exit(self, event):  # wxGlade: MainFrame.<event_handler>
        self.Close()
        event.Skip()

    def OnNewSetpoint(self, newSetpoint):
        self.map.newSetpoint = newSetpoint
        self.UpdateSetpoint()

    def UpdateSetpoint(self):
        s = "New set point: "
        if (self.map.newSetpoint < 0):
            s += "-"
            self.btnSetUpper.Enable(False)
            self.btnSetLower.Enable(False)
            self.btnCancel.Enable(False)
        else:
            s += str(round(self.map.newSetpoint))+"°"
            self.btnSetUpper.Enable(True)
            self.btnSetLower.Enable(True)
            self.btnCancel.Enable(True)
        self.lblNewSetPoint.SetLabel(s)
        self.map.Refresh()

    def on_upper_ref(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("runCalibrationUp")
        event.Skip()

    def on_upper_stop(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("setRotorStop")
        event.Skip()

    def on_lower_ref(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("runCalibrationDown")
        event.Skip()

    def on_lower_stop(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("setRotorStop")
        event.Skip()

    def on_set_upper(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("setRotorUp "+str(self.map.newSetpoint))
        self.map.newSetpoint = -1
        self.UpdateSetpoint()       
        event.Skip()

    def on_set_lower(self, event):  # wxGlade: MainFrame.<event_handler>
        rotor.SendCommand("setRotorDown "+str(self.map.newSetpoint))
        self.map.newSetpoint = -1
        self.UpdateSetpoint()
        event.Skip()

    def updateDisplay(self, msg):
        v = rotor.Values["UpperSetpoint"]
        self.lblUpSetPoint.SetLabel( f"Set Point: {v:.1f}°")
        self.map.upperSetpoint = v
        v = rotor.Values["UpperPosition"]
        self.lblUpPosition.SetLabel( f"Position: {v:.1f}°")
        self.map.upperPosition = v
        v = rotor.Values["UpperCurrent"]
        self.lblUpCurrent.SetLabel( f"Current: {v} mA")
        v = rotor.Values["UpperActive"]
        self.btnUpperStop.Enable(v!=0)
        self.btnUpperStop.SetBackgroundColour(wx.NullColour if v==0 else wx.Colour(255,142,127))
        v = rotor.Values["UpperReferenced"]
        self.btnUpperRef.SetBackgroundColour( wx.Colour(255,142,127) if v==0 else wx.Colour(127,255,0) )
        v = rotor.Values["LowerSetpoint"]
        self.lblDownSetPoint.SetLabel( f"Set Point: {v:.1f}°")
        self.map.lowerSetpoint = v
        v = rotor.Values["LowerPosition"]
        self.lblDownPosition.SetLabel( f"Position: {v:.1f}°")
        self.map.lowerPosition = v
        v = rotor.Values["LowerCurrent"]
        self.lblDownCurrent.SetLabel( f"Current: {v} mA")
        v = rotor.Values["LowerActive"]
        self.btnLowerStop.Enable(v!=0)
        self.btnLowerStop.SetBackgroundColour(wx.NullColour if v==0 else wx.Colour(255,142,127))
        v = rotor.Values["LowerReferenced"]
        self.btnLowerRef.SetBackgroundColour( wx.Colour(255,142,127) if v==0 else wx.Colour(127,255,0) )
        self.map.Refresh()
        print("Update") 

    def on_set_location(self, event):  # wxGlade: MainFrame.<event_handler>
        p = wx.Point(-1,30)
        dlg = wx.TextEntryDialog(self, 'Enter new location','New location', pos=p)
        dlg.SetValue(self.map.location)
        dlg.SetPosition(p)
        if dlg.ShowModal() == wx.ID_OK:
            self.map.SetLocation(dlg.GetValue())
            self.btnSetLocation.SetLabel("Location: "+self.map.location)
            self.map.Refresh()
        dlg.Destroy()
        event.Skip()

# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)
    rotor = rotorCom.RotorCom("100.64.23.228",23)
    app = MyApp(0)
    app.MainLoop()
    rotor.stop()
